keys:
  - &users:
    - &bastian age1h64vw9c7pxae4pzvaz456hh9sm6jk73px4wc6stxcpxk3apytatq0k5xxf
  - &hosts:
    - &lambda age1qssa558zq6qkaakplmkemet0jah6mh5rr5wxt0sl9fvq2nuuffps9fl4gx

creation_rules:
  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *bastian
          - *lambda
