[build]
rustc-wrapper = "/home/bastian/.cargo/bin/sccache"
jobs = 4

rustflags = [
    "-Wclippy::pedantic",
    "-Wclippy::nursery",
    "-Wclippy::unwrap_used",
    "-Wclippy::expect_used",
]

[term]
color = "always"

