[build]
jobs = 24

rustflags = [
    "-Dclippy::enum_glob_use", # Disallow use of `use` of all enums.
    "-Dclippy::pedantic",      # Enable all pedantic lints.
    "-Dclippy::nursery",       # Enable all nursery lints.
    "-Dclippy::unwrap_used",   # Disallow use of `unwrap`.
]

[term]
color = "always"

