name: Flake Update
on:
  workflow_dispatch: # Allows manual triggering.
  schedule:
    - cron: "0 0 * * MON" # Runs weekly on Monday at 00:00.

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created.
          pr-labels: | # Labels to be set on the PR.
            dependencies
            automated
